window.SCTOL_SERVICE_CATALOG = {
  aliases: [
    { canonical: "ABEMA", re: /abema|ア\s*ベ\s*マ/i },
    { canonical: "LINE_COIN", re: /l[i1l][nｍm]e\s*c[o0]in|line\s*coin/i },
    { canonical: "MINNA_BANK", re: /み\s*ん\s*な\s*の\s*銀\s*行|minna\s*no\s*ginko/i },
    { canonical: "ICLOUD", re: /icloud\+?|i\s*cloud|i\s*cl0ud/i },
    { canonical: "APP_STORE", re: /app\s?store|itunes/i },
    { canonical: "APPLE_MUSIC", re: /apple\s?music/i },
    { canonical: "APPLE_ONE", re: /apple\s?one/i },
    { canonical: "APPLE_DEVELOPER", re: /developer\s*program|デベロッパ/i },
    { canonical: "YOUTUBE", re: /youtube/i },
    { canonical: "NETFLIX", re: /netflix/i },
    { canonical: "CHATGPT", re: /chatgpt|openai/i },
    { canonical: "LIFE_CYCLE", re: /life\s*cycle/i },
  ],
  display: {
    ABEMA: "ABEMA",
    LINE_COIN: "LINE Coin",
    MINNA_BANK: "みんなの銀行",
    ICLOUD: "iCloud",
    APP_STORE: "AppStore",
    APPLE_MUSIC: "Apple Music",
    APPLE_ONE: "Apple One",
    APPLE_DEVELOPER: "Apple Developer Program",
    YOUTUBE: "YouTube",
    NETFLIX: "Netflix",
    CHATGPT: "ChatGPT",
    LIFE_CYCLE: "Life Cycle",
  },
};
